development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: ckbearn_development

test:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: ckbearn

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: ckbearn
